name: update-pref-docker-only

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build_docker:  
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
          tags: sliamb/paopao-pref:latest
  
  # build_mark:
  #   needs: build_docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         context: "{{defaultContext}}:mark_builder"
  #         platforms: linux/amd64
  #         tags: sliamb/mark_builder:latest

  build_runner:
    needs: build_docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DATA }}
          token: ${{ secrets.GH_TOKEN }}
          path: 'data'
      - name: cp
        run: cp ./data/*.rules ./mark_builder/
      - name: build runner
        run: cd mark_builder && docker build --no-cache --progress=plain -t runner .
      - name: login docker
        run: echo ${{ secrets.TDOCKERHUB_TOKEN }} | docker login ${{ secrets.TDOCKERHUB_LOGIN }} --username ${{ secrets.TDOCKERHUB_USERNAME }} --password-stdin
      - name: tag
        run: docker tag runner ${{ secrets.TDOCKERHUB_TAG_RUNNER }}
      - name: push
        run: docker push ${{ secrets.TDOCKERHUB_TAG_RUNNER }} >/dev/null