name: dnscrypt_resolver_test
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'LICENSE'
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  check_dnscrypt_resolver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: check dnscrypt_resolver
      run: sh dnscrypt_resolver/check.sh
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Github Actions
        author_email: actions@github.com
        committer_email: actions@github.com
    - name: Flash CDN
      run: |
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/trackerslist.txt.xz &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/trackerslist.txt.xz.sha256sum