name: mark-update-4

on:
  workflow_dispatch:
  schedule:
    - cron: '30 01 * * 4'
permissions:
  contents: write

jobs:
  update_mark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update data
      run: sh update_mark.sh
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Github Actions
        author_email: actions@github.com
        committer_email: actions@github.com
  build_mark:
    needs: update_mark
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:mark_builder"
          platforms: linux/amd64
          tags: sliamb/mark_builder:latest