name: mark-update-4

on:
  workflow_dispatch:
  schedule:
    - cron: '01 19 * * 4'
permissions:
  contents: write

jobs:
  build_mark:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:mark_builder"
          platforms: linux/amd64
          tags: sliamb/mark_builder:latest
  update_data:
    needs: build_mark
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update mark
      run: docker run -v $(pwd):/pub -e DNS_LIMIT=25 sliamb/mark_builder
    - run: git pull
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Github Actions
        author_email: actions@github.com
        committer_email: actions@github.com