name: mark-update-4

on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * 4'
permissions:
  contents: write

jobs:
  update_mark:
    runs-on: ubuntu-latest
    steps:
      - name: login docker
        run: echo ${{ secrets.TDOCKERHUB_TOKEN }} | docker login ${{ secrets.TDOCKERHUB_LOGIN }} --username ${{ secrets.TDOCKERHUB_USERNAME }} --password-stdin
      - name: Checkout code
        uses: actions/checkout@v3
      - name: pull
        run: docker pull ${{ secrets.TDOCKERHUB_TAG }} >/dev/null
      - name: run
        run: docker run -d --name data ${{ secrets.TDOCKERHUB_TAG }}
      - name: cp global_mark.dat.sha256sum
        run: docker cp data:/pub/global_mark.dat.sha256sum global_mark.dat.sha256sum
      - name: cp global_mark.dat
        run: docker cp data:/pub/global_mark.dat global_mark.dat
      - uses: EndBug/add-and-commit@v9
        with:
         author_name: Github Actions
         author_email: actions@github.com
         committer_email: actions@github.com
         
  # build_mark:
  #   needs: update_mark
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         context: "{{defaultContext}}:mark_builder"
  #         platforms: linux/amd64
  #         tags: sliamb/mark_builder:latest

  build_runner:
    # needs: build_mark
    needs: update_mark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DATA }}
          token: ${{ secrets.GH_TOKEN }}
          path: 'data'
      - name: cp
        run: cp ./data/*.rules ./mark_builder/
      - name: build runner
        run: cd mark_builder && docker build --no-cache --progress=plain -t runner .
      - name: login docker
        run: echo ${{ secrets.TDOCKERHUB_TOKEN }} | docker login ${{ secrets.TDOCKERHUB_LOGIN }} --username ${{ secrets.TDOCKERHUB_USERNAME }} --password-stdin
      - name: tag
        run: docker tag runner ${{ secrets.TDOCKERHUB_TAG_RUNNER }}
      - name: push
        run: docker push ${{ secrets.TDOCKERHUB_TAG_RUNNER }} >/dev/null
