name: update_runner-docker-only

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DATA }}
          token: ${{ secrets.GH_TOKEN }}
          path: 'data'
      - name: cp
        run: cp ./data/*.rules ./mark_builder/
      - name: build runner
        run: cd mark_builder && docker build --no-cache --progress=plain -t runner .
      - name: login docker
        run: echo ${{ secrets.TDOCKERHUB_TOKEN }} | docker login ${{ secrets.TDOCKERHUB_LOGIN }} --username ${{ secrets.TDOCKERHUB_USERNAME }} --password-stdin
      - name: tag
        run: docker tag runner ${{ secrets.TDOCKERHUB_TAG_RUNNER }}
      - name: push
        run: docker push ${{ secrets.TDOCKERHUB_TAG_RUNNER }} >/dev/null