name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '06 06 01 * *'
permissions:
  contents: write

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - name: build binary
      run: sh release.sh
    - name: Set variables
      run: echo "TAG_NAME="data"-$(date +%Y%m%d-%s)" >> $GITHUB_ENV
    - name: Upload files to GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: ./build/*
        tag: ${{ env.TAG_NAME }}
    - name: Remove old release
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}